version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24

services: 
  bootnode:
    container_name: bootnode
    image: hyperledger/besu
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json --rpc-http-enabled --rpc-ws-enabled \
        --host-allowlist="*" --rpc-http-cors-origins="all" \
        --revert-reason-enabled \
        --rpc-http-api=ETH,NET,IBFT,WEB3,DEBUG,TXPOOL;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Node-1/data:/opt/besu/data
      - ./auth.toml:/opt/besu/auth.toml
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    networks:
      besu-network:
        ipv4_address: 172.16.100.40

  node2:
    container_name: node2
    image: hyperledger/besu

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
         --min-gas-price=0 \
         --host-allowlist="*" --rpc-http-cors-origins="all" \
         --bootnodes=enode://749b629914a70123cb752d8f5097264d283420358d80349cadb10c5bdd5c920b9ddcbbb11d61c34d713ed6457780e953dabd30c1e6b4ed15d5fa8d895f53643b@172.16.100.40:30303 --p2p-port=30303;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Node-2/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
    ports:
      - 8547:8545
      - 30304:30303
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.100.41

  
  node3:
    container_name: node3
    image: hyperledger/besu

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
         --min-gas-price=0 \
         --host-allowlist="*" --rpc-http-cors-origins="all" \
         --bootnodes=enode://749b629914a70123cb752d8f5097264d283420358d80349cadb10c5bdd5c920b9ddcbbb11d61c34d713ed6457780e953dabd30c1e6b4ed15d5fa8d895f53643b@172.16.100.40:30303 --p2p-port=30303;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Node-3/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
    ports:
      - 8548:8545
      - 30305:30303
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.100.42

  node4:
    container_name: node4
    image: hyperledger/besu

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
         --host-allowlist="*" --rpc-http-cors-origins="all" \
         --min-gas-price=0 \
         --bootnodes=enode://749b629914a70123cb752d8f5097264d283420358d80349cadb10c5bdd5c920b9ddcbbb11d61c34d713ed6457780e953dabd30c1e6b4ed15d5fa8d895f53643b@172.16.100.40:30303 --p2p-port=30303;
    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./Node-4/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
    ports:
      - 8549:8545
      - 30306:30303
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.100.43
